config/urls.py
from django.contrib import admin
from django.urls import path, include
#from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
#    path('pybo/', views.index), # django프로젝트 전체에 대한 url패턴을 매핑하는 파일. 각 앱별로 각 urls.py에 매핑필요하다.
    path('pybo/', include('pybo.urls')), # http://localhost:포트/pybo/...로 시작하는 url매핑정보는 pybo앱 밑의 urls.py에 있다!
]

pybo/urls.py
from django.urls import path

from . import views #현재 패키지의 views모듈(views.py)을 import

app_name = 'pybo' # 도메인명:포트번호/앱이름(=pybo), 즉, http://localhost:8000/pybo/xxx 요청시

urlpatterns = [

    path('',views.index, name='index'), # xxx가 비었으면, views.py의 index라는 함수를 호출, http://localhost:8000/pybo/ 라는 url에 index라는 별칭을 부여. 추후, 템플릿에서 <a href="{% url 'detail' question.id %}"> 태그에서 detail 이라는 name을 사용가능하다.
    path('<int:question_id>/',views.detail, name='detail'), # xxx가 int형의 question_id라는 수자이면, views.py의 detail라는 함수를 호출, http://localhost:8000/pybo/숫자../라는 패턴의 url에 detail이라는 별칭을 부여함.
    path('answer/create/<int:question_id>/',views.answer_create, name='answer_create'), # xxx가 answer/create/int형 question_id라는 숫자이면, views.py의 answer_create라는 함수를 호출, http://localhost:8000/pybo/answer/create/숫자.../ 라는 패턴의 url에는 answer_create라는 별핑을 부여함.
    path('question/create/',views.question_create, name='question_create'), # xxx가 question/create/int형 question_id라는 숫자이면, views.py의 question_create라는 함수를 호출, http://localhost:8000/pybo/answer/create/숫자.../ 라는 패턴의 url에는 answer_create라는 별핑을 부여함.

               ]

pybo/models.py
from django.db import models

# Create your models here.
# model은 데이터를 다룬다
# model의 모든 클래스는 db table의 필드 정보를 갖는다
# models에 작성한것은 선언일뿐, 실제 db 테이블을 생성하지는 않는다.
# 실제 테이블은
# 1. pybo앱을 config/settings.py의 INSTALLED_APPS 항목에 'pybo.apps.PyboConfig' 클래스(pybo/apps.py에 있음)를 추가하고
# 2. (가상환경)cmd에서 python manage.py makemigtations(pybo/migrations/0001_initial.py생성됨. 설계도임.), python manage.py migrate(실제 테이블생성)를 수행해 주어야 한다. ddl문은 python manage.py pybo 0001을 통해 확인가능

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject #Question.objects.all() 함수 호출시 <QuerySet [<Question: Question object (1)>, <Question: Question object (2)>]>... 처럼 조회되니 불편하다.
                            #<QuerySet [<Question: pybo가 무엇인가요?>, <Question: 장고 모델 질문입니다.>]> 의 형태로 조회되게 하려고.

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

pybo/forms.py
from django import forms
from pybo.models import Question, Answer

# form 이란: url요청시, 파라미터 값 체크, HTML 자동생성, 데이터 저장(연결된 model을 이용하여) form은 일반form, 모델form으로 나뉨. 데이터저장+추후 템플릿에서 HTML생성
class QuestionForm(forms.ModelForm): #이 클래스는 모델form을 상속함(forms.ModelForm)
    class Meta: #QuestionForm은 모델폼으로, inner클래스가 필수임. 사용할 모델(Question)과 모델(Question)의 속성을 아래 처럼 적여야 함.
        model = Question # QuestionForm이라는 모델폼은 Question이라는 모델(데이터를 담당)과 연결되는 폼이다! 이 폼에서 사용할 모델:Question
        fields = ['subject','content'] # QuestionForm이라는 모델폼은 속성으로 Question모델의 subject와 content라는 속성 2개를 사용한다! 이 폼에서 사용할 속성:subject,content
        labels = {
            'subject': '제목',
            'content': '내용',
        }
"""
        widgets = {
            'subject': forms.TextInput(attrs={'class':'form-control'}),
            'content': forms.Textarea(attrs={'class':'form-control','rows':10})
        }
"""

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content':'답변내용',
        }

pybo/views.py
#from django.http import HttpResponse

from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Question # views는 로직, 로직에서 데이터를 다루기 위해, models 모듈의 Question 클래스를 import
from .forms import QuestionForm, AnswerForm # forms.py의 QuestionForm이라는 클래스를 import

# views.py는 로직을 담당한다.

def index(request):
#    return HttpResponse("안녕하세요 pybo에 오신것을 환영합니다.")
    """
    pybo 목록 출력
    """
    question_list = Question.objects.order_by('-create_date')  # Question이라는 모델은 models.py에 정의되어 있다. 모든 데이터를 조회함. models.py에서 보면 모든 subject만 리턴해준다.
    context = {'question_list':question_list}                  # 템플릿에서 받아서 쓸 데이터를 딕셔너리 형태로! 조회한 모든 데이터를 딕셔너리 형태로 저장.
    return render(request, 'pybo/question_list.html', context) # 템플릿은 templates/pybo/question_list.html이다. config/settings.py에 TEMPLATES = [ ... 'DIRS': [BASE_DIR / 'templates'], ... ] 정의되어 있다.

def detail(request, question_id):
    """
    pybo 내용 출력
    """
#    question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id) # Question이라는 모델은 models.py에 정의되어 있다., question_id가 없는 숫자이면, 404에러를 뱉기위해
    context = {'question':question} # 호출될 템플릿에서 받아서 사용할 data를 딕셔너리 형태로 만들어서 넘긴다! 호출된 템플릿에서는 넘겨지는 딕셔너리의 key.value형태로 데이터를 끄집어낸다. 키:question, value:question.subject/question.content/question.create_date
    #print(context)
    return render(request,'pybo/question_detail.html',context) # 사용할 템플릿은 templates/pybo/question_detail.html이다

def answer_create(request, question_id):
    """
    pybo 답변등록

    question = get_object_or_404(Question, pk=question_id) # Question이라는 모델은 models.py에 정의되어 있다., question_id가 없는 숫자이면, 404에러를 뱉기위해
    question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    return redirect('pybo:detail', question_id=question.id) # name='detail' 이라는 url패턴을 urls.py에서 찾아서, 해당 url주소 패턴에 해당하는 로직을 views.py에서 찾아서 동작시켜라.
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail',question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request,'pybo/question_detail.html', context)

def question_create(request):
    """
    pybo 질문등록
    """
    if request.method == "POST":
        form = QuestionForm(request.POST)  # forms.py에 정의된 QuestionForm클래스를 객체생성, 해당 객체는 어떤 model을 사용하는지(모델명:Question)/어떤 속성(필드:subject/content)를 사용하는지 정의하고 있다.

        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
        context = {'form':form}
    return render(request,'pybo/question_form.html',{'form': form}) # 사용할 템플릿:pybo/question_form.html, 전달할 객체:form, 즉, question_form.html에 form이라는 객체를 전달.

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}

base.html을 상속받은후 아래 알맹이만 작성함

<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}

        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}

        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>

{% endblock %}

templates/pybo/question_detail_bkp.html
{% load static %} <!-- 스타일시트 같은 static파일을 참조하겠다-->
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> <!-- 종류는 stylesheet이고, 참조할 파일 위치는 static 폴더 밑의 sytle.css파일이다 -->

======================================================================================================
bootstrap 스타일시트 적용후

<h1>{{ question.subject }}</h1>

<div>
    {{question.content}}
</div>

<h5> {{ question.answer_set.count }}개의 답변이 있습니다.</h5>
<div>
    <ul>
        {% for answer in question.answer_set.all %}
            <li> {{ answer.content }} </li>
        {% endfor %}
    </ul>
</div>
<form action="{% url 'pybo:answer_create' question.id %}" method="post"> <!-- 호출할 url은 pybo/urls.py의 name='answer_create' url패턴을 참고한다. -->
    {% csrf_token %}
    <textarea name="content" id="content" rows="15"></textarea>
    <input type="submit" value="답변등록">
</form>

======================================================================================================
bootstrap 스타일시트 적용후

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>

templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3"> <!-- 보통 form태크에는 action='abc.html'처럼 목적지URL을 정의하지만, 지금처럼 정의하지 않으면 현 URL이 목적지임-->
                                                <!-- from method="post" class="post-form my-3" action="{주석주의% url 'pybo:question_form.html'%주석주의}" 처럼 명확하게 지정해도 되나, 질문등록만 사용가능. 앞으로 질문수정 기능이 이 템플릿에 구현되면 다른 목적지 URL이 되어야 하니, 이렇게는 하지 말자-->
                                                <!-- 동일한 템플릿을 여러 기능에서 함께 사용할 경우에는 이처럼 form의 action 속성을 비워라-->
        {% csrf_token %}
        <!--{{ form.as_p }}--> <!-- 본 html을 호출한 def에서 어떤 모델을 사용하여 form을 만들었는지 정의하고, 해당 form을 html에 넘겨줌. 이 form은 모델form으로 1.모델(사용된 모델명:Question)명과 속성(필드:subject/content)정보를 갖는다. 2.HTML을 생성해준다.-->
                        <!-- subject,content속성에 해당하는 HTML코드를 자동 생성(보여줄 항목은 form에서 지정한 모델 (Question)의 속성들임)-->

        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->

        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>

        <button type="submit" class="btn btn-primary">저장하기</button> <!-- 버튼누르면, 자기자신의 url을 요청. 그럼 urls.py에 정의된 패턴(자기자신url패턴이고 /question/create/)을 찾는다. -->
    </form>
</div>

{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% block content %}


base.html을 상속받은후 아래 알맹이만 작성함

        <div class="container my-3">
            <table class="table">
                <thead>
                <tr class="thead-dark">
                    <th>번호</th>
                    <th>제목</th>
                    <th>작성일시</th>
                </tr>
                </thead>
                <tbody>
                {% if question_list %}
                {% for question in question_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>
                        <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a> <!-- urls.py에 name='detail'이라는 별칭을 가진 url패턴이 목적지 url이다. question.id값을 url에 같이 넘긴다.-->
                    </td>
                    <td>{{ question.create_date }}</td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="3">질문이 없습니다.</td>
                </tr>
                {% endif %}
                </tbody>
            </table>
            <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문등록하기</a>
        </div>

{% endblock %}

templates/pybo/question_list_bkp.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

bootstrap 스타일시트 적용전

{% if question_list %}
    <ul>
        {% for question in question_list %}
    <!--<li><a href="/pybo/{{ question.id }}/">{{ question.subject }}</a></li> -->
        <li><a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a> {{ question.create_date }} </li> <!--호출할 url 은 pybo/urls.py의 name='detail'을 갖는 url패턴을 참조 -->

        {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %}

<h1>{{ question.subject }}</h1>
<div>
    {{ question.content }}
</div>

======================================================================================================
bootstrap 스타일시트 적용후

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>

templates/pybo/std.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>

(... 생략 ...)

</body>
</html>